services:
  nginx:
    image: nginx:alpine
    deploy:
      mode: global
      placement:
        constraints: [node.labels.type == web]
      update_config:
        parallelism: 1
        delay: 10s
    ports:
      - "8080:80"
    configs:
      - source: nginx_conf
        target: /etc/nginx/conf.d/default.conf
    volumes:
      - type: bind
        source: /mnt/efs
        target: /var/www/html
    networks:
      - webnet

  php-fpm:
    image: php:8.2-fpm-alpine
    deploy:
      mode: global
      placement:
        constraints: [node.labels.type == web]
    command: >
      sh -c "docker-php-ext-install mysqli && php-fpm"
    volumes:
      - type: bind
        source: /mnt/efs
        target: /var/www/html
    networks:
      - webnet

  mariadb:
    image: mariadb:10.11
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.type == db]
    environment:
      MARIADB_ROOT_PASSWORD: "0117"
      MARIADB_DATABASE: "miBBDD"
      MARIADB_USER: "manuel"
      MARIADB_PASSWORD: "0117"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - webnet

configs:
  nginx_conf:
    file: ./nginx_conf/default.conf

volumes:
  db-data:

networks:
  webnet:
    driver: overlay