

services:
  nginx:
    image: nginx:alpine
    deploy:
      mode: global
      placement:
        constraints: [node.labels.type == web]
      update_config:
        parallelism: 1
        delay: 10s
    ports:
      - "80:80"
    configs:
      - source: nginx_conf
        target: /etc/nginx/conf.d/default.conf
    volumes:
      - web-efs:/var/www/html
    networks:
      - webnet

  php-fpm:
    image: php:8.2-fpm-alpine
    deploy:
      mode: global
      placement:
        constraints: [node.labels.type == web]
    volumes:
      - web-efs:/var/www/html
    networks:
      - webnet

  mariadb:
    image: mariadb:10.11
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.type == db]
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD_ROOT_MYSQL}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${USUARIO_MYSQL}
      MYSQL_PASSWORD: ${PASSWORD_USUARIO_MYSQL}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - webnet

configs:
  nginx_conf:
    file: ./nginx_conf/default.conf

volumes:
  web-efs:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=fs-0ab49c3a2e7eb3657.efs.us-east-1.amazonaws.com,nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2"
      device: ":/"
  
  db-data:

networks:
  webnet:
    driver: overlay
